/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aggregator;

import aggregator.configs.KafkaProperties;
import aggregator.processors.SubmissionProcessor;

import java.util.Properties;

import org.apache.kafka.streams.KafkaStreams;
import org.apache.kafka.streams.StreamsBuilder;
import org.apache.kafka.streams.errors.StreamsUncaughtExceptionHandler;

public class App {
    public static void main(String[] args) {
        KafkaProperties kafkaProps = new KafkaProperties();

        Properties props = kafkaProps.getKafkaStreamsProperties();

        StreamsBuilder builder = new StreamsBuilder();
        SubmissionProcessor submissionProcessor = new SubmissionProcessor(kafkaProps);
        submissionProcessor.buildSubmissionStream(builder);

        KafkaStreams streams = new KafkaStreams(builder.build(), props);
        submissionProcessor.setStreams(streams);

        streams.setUncaughtExceptionHandler(ex -> {
            System.out.println(ex);
            return StreamsUncaughtExceptionHandler.StreamThreadExceptionResponse.SHUTDOWN_APPLICATION;
        });
        streams.start();

        Runtime.getRuntime().addShutdownHook(new Thread(streams::close));
        System.out.println(kafkaProps.getApplicationId() + " is running...");
    }
}
